apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetysearch
  labels:
    app: tweetysearch
  namespace: tweety-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetysearch
  template:
    metadata:
      labels:
        app: tweetysearch
    spec:
      containers:
        - name: tweetysearch
          image: karthiv89/tweetysearch:1.0
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tweetysearch
  namespace: tweety-microservice
spec:
  selector:
    app: tweetysearch
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
